### ISSUE TITLE
Add `doctest` to test code examples in documentation

### ISSUE THREAD

**Issue by nh916** [C-Accel-CRIPT/Python-SDK#114]
## Description

```yaml
name: Doctest

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run doctest
        run: |
          find . -name '*.py' -type f -exec python -m doctest -v {} +
```

This configuration uses the `find` command to locate all `.py` files in your repository recursively and executes `doctest` on each of them. The `+` at the end of the `find` command ensures that multiple files are passed to `doctest` at once, which can improve performance.

Make sure to update the `python-version` and `pip install` steps according to your project's requirements.

With this setup, all Python files in your repository with docstrings containing doctests will be tested as part of the CI process.
