### ISSUE TITLE
Add social media and resources to Documentation links

### ISSUE THREAD

**Issue by nh916** [C-Accel-CRIPT/Python-SDK#120]
## Description
Add social media, logos, and resources links to documentation

```yaml
# This links the CRIPT logo to the CRIPT homepage
extra:
  homepage: https://criptapp.org
#  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/squidfunk
#      name: squidfunk on Twitter
copyright: © 2023 MIT | All Rights Reserved
```
