### ISSUE TITLE
Pipeline Idea: Add Test Coverage

### ISSUE THREAD

**Issue by nh916** [C-Accel-CRIPT/Python-SDK#62]
# Description
It is good to see that our tests have passed, but it might also be good to see how much of the code was tested which could highlight areas that need testing or any false optimism that the tests are providing and create a more accurate view.

**Comment by nh916** [comment]
possible GitHub workflow

```yaml
name: Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=70
```
